SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

CREATE DATABASE `ccdash` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `ccdash`;

CREATE TABLE `agents` (
  `nr` tinyint(4) NOT NULL,
  `name` varchar(50) COLLATE utf8_bin NOT NULL,
  `dnd` tinyint(4) NOT NULL,
  `offhook` tinyint(4) NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`nr`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
SET FOREIGN_KEY_CHECKS=1;
